# Gradle JVM arguments
#org.gradle.jvmargs=-Xmx1536M
#org.gradle.jvmargs=-Xmx4096m
org.gradle.daemon=true
# Use AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=false
# Suppress compile SDK warnings (if using newer SDKs)
android.suppressUnsupportedCompileSdk=35
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g
kotlin.jvm.target.validation.mode=IGNORE
