// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEscP-oNZjwQEHMbjyTUK2UYyoAKA96fM',
    appId: '1:932653372426:android:a482e29670aef91c12fbf3',
    messagingSenderId: '932653372426',
    projectId: 'more-mito-app',
    storageBucket: 'more-mito-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApwaTh5BjWIzSjR-Cv8FzKUzRCCq5nAJY',
    appId: '1:932653372426:ios:763725431944f39c12fbf3',
    messagingSenderId: '932653372426',
    projectId: 'more-mito-app',
    storageBucket: 'more-mito-app.firebasestorage.app',
    iosBundleId: 'com.moremito.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfU7Y8vD_n3lJomJRAuPfqTDInoqbuyvs',
    appId: '1:932653372426:web:673b072a9e49703612fbf3',
    messagingSenderId: '932653372426',
    projectId: 'more-mito-app',
    authDomain: 'more-mito-app.firebaseapp.com',
    storageBucket: 'more-mito-app.firebasestorage.app',
    measurementId: 'G-959ZE0M107',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApwaTh5BjWIzSjR-Cv8FzKUzRCCq5nAJY',
    appId: '1:932653372426:ios:763725431944f39c12fbf3',
    messagingSenderId: '932653372426',
    projectId: 'more-mito-app',
    storageBucket: 'more-mito-app.firebasestorage.app',
    iosBundleId: 'com.moremito.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfU7Y8vD_n3lJomJRAuPfqTDInoqbuyvs',
    appId: '1:932653372426:web:40b2dc325505c1db12fbf3',
    messagingSenderId: '932653372426',
    projectId: 'more-mito-app',
    authDomain: 'more-mito-app.firebaseapp.com',
    storageBucket: 'more-mito-app.firebasestorage.app',
    measurementId: 'G-WJ8GEF4ZQV',
  );

}